### ISSUE TITLE
Prospect ??

### ISSUE THREAD

**Issue by catlynce** [PliegerNicolas/MuWe#44]
Could you, please, explain by your own words what would be this page ?

**Comment by PliegerNicolas** [comment]
We wanted to add a post, ... system. Each user on his profile page can post links (or directly upload vidéos that would be amazing). As a User comming into a town you'd like to know what kind of music players are around you and what the community you're in is capable of (this could relate with the organisator_id in event model). So imagine you're in lisbon, the page would display to you the latest uploaded vidéos from the people in Lisbon (50km around you or something)
